import DicodingLogo from "../assets/certifications/dicoding.png";
import SoloLearnLogo from "../assets/certifications/sololearn.webp";
import DQLabLogo from "../assets/certifications/dqlab.png";
import GoogleLogo from "../assets/certifications/google.webp";
import GSALogo from "../assets/experiences/gsa.png";
import AWSLogo from "../assets/certifications/aws.png";

export const CERTIFICATION_DATA = [
  {
    id: "cert-26",
    title: "Belajar Fundamental Back-End dengan JavaScript",
    issuer: "Dicoding Indonesia",
    date: "December 2025",
    credentialId: "JLX15Y915Z72",
    link: "https://www.dicoding.com/certificates/JLX15Y915Z72",
    logo: DicodingLogo,
  },
  {
    id: "cert-25",
    title: "GSA Tech Update on AI mode, Gemini 3, and Nano Banana Pro Workshop",
    issuer: "Google Student Ambassador Indonesia",
    date: "December 2025",
    credentialId: "-",
    link: "https://www.linkedin.com/in/louisnath/details/certifications/",
    logo: GSALogo,
  },
  {
    id: "cert-24",
    title: "DevFest Cloud Surabaya 2025",
    issuer: "Google Developer Groups Cloud Surabaya",
    date: "November 2025",
    credentialId: "-",
    link: "https://www.linkedin.com/in/louisnath/details/certifications/", 
    logo: GoogleLogo,
  },
  {
    id: "cert-23",
    title: "GSA AI Mini Bootcamp with Friends of Google",
    issuer: "Google Student Ambassador Indonesia",
    date: "November 2025",
    credentialId: "-", 
    link: "https://www.linkedin.com/in/louisnath/details/certifications/",
    logo: GSALogo,
  },
  {
    id: "cert-22",
    title: "Belajar Back-End Pemula dengan JavaScript", 
    issuer: "Dicoding Indonesia",
    date: "October 2025",
    credentialId: "72ZDKKNWVPYW",
    link: "https://www.dicoding.com/certificates/72ZDKKNWVPYW",
    logo: DicodingLogo,
  },
    {
    id: "cert-21",
    title: "Belajar Dasar Cloud dan Gen AI di AWS",
    issuer: "Dicoding Indonesia",
    date: "October 2025",
    credentialId: "KEXL2YV3WZG2",
    link: "https://www.dicoding.com/certificates/KEXL2YV3WZG2",
    logo: DicodingLogo,
  },
  {
    id: "cert-20",
    title: "Belajar Fundamental Aplikasi Web dengan React",
    issuer: "Dicoding Indonesia",
    date: "October 2025",
    credentialId: "1OP8JW3ELPQK",
    link: "https://www.dicoding.com/certificates/1OP8JW3ELPQK",
    logo: DicodingLogo,
  },
  {
    id: "cert-19",
    title: "Gemini Certified Educator",
    issuer: "Google for Education",
    date: "October 2025",
    credentialId: "163217761",
    link: "https://edu.google.accredible.com/755b32bf-4f9a-4ce7-8cbe-2065d0af613e#acc.birSFnVj", 
    logo: GoogleLogo,
  },
  {
    id: "cert-18",
    title: "Gemini Certified University Student",
    issuer: "Google",
    date: "October 2025",
    credentialId: "162980289",
    link: "https://edu.google.accredible.com/5ae84e45-f8c9-4cd7-8dcb-d16276a9d1e2#acc.B1lRmypL", 
    logo: GoogleLogo,
  },
  {
    id: "cert-17",
    title: "Belajar Dasar Pemrograman JavaScript",
    issuer: "Dicoding Indonesia",
    date: "September 2025",
    credentialId: "1RXYQOKVKZVM",
    link: "https://www.dicoding.com/certificates/1RXYQOKVKZVM",
    logo: DicodingLogo,
  },
  {
    id: "cert-16",
    title: "Belajar Membuat Aplikasi Web dengan React",
    issuer: "Dicoding Indonesia",
    date: "September 2025",
    credentialId: "07Z6JVO9JXQR",
    link: "https://www.dicoding.com/certificates/07Z6JVO9JXQR",
    logo: DicodingLogo,
  },
  {
    id: "cert-15",
    title: "Belajar Membuat Front-End Web untuk Pemula",
    issuer: "Dicoding Indonesia",
    date: "September 2025",
    credentialId: "ERZR2G21QPYV",
    link: "https://www.dicoding.com/certificates/ERZR2G21QPYV",
    logo: DicodingLogo,
  },

  {
    id: "cert-14",
    title: "Belajar Dasar Git dengan GitHub",
    issuer: "Dicoding Indonesia",
    date: "August 2025",
    credentialId: "MRZM6KO2RPYQ",
    link: "https://www.dicoding.com/certificates/MRZM6KO2RPYQ",
    logo: DicodingLogo,
  },
  {
    id: "cert-13",
    title: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
    issuer: "Dicoding Indonesia",
    date: "August 2025",
    credentialId: "N9ZO27OG6PG5",
    link: "https://www.dicoding.com/certificates/N9ZO27OG6PG5",
    logo: DicodingLogo,
  },
  {
    id: "cert-12",
    title: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
    issuer: "Dicoding Indonesia",
    date: "August 2025",
    credentialId: "KEXL2G7J0ZG2",
    link: "https://www.dicoding.com/certificates/KEXL2G7J0ZG2",
    logo: DicodingLogo,
  },
  {
    id: "cert-11",
    title: "Build Real World AI Applications with Gemini and Imagen",
    issuer: "Google Cloud",
    date: "February 2025",
    credentialId: "-", 
    link: "https://www.credly.com/badges/4cee9841-101a-4ee8-8528-c9d095508df3/linked_in_profile",
    logo: GoogleLogo,
  },
  {
    id: "cert-10",
    title: "Prompt Design in Vertex AI Skill Badge",
    issuer: "Google Cloud",
    date: "February 2025",
    credentialId: "-", 
    link: "https://www.credly.com/badges/c129f27d-5678-42e3-a011-4ff89cdf240d/linked_in_profile",
    logo: GoogleLogo,
  },
  {
    id: "cert-09",
    title: "Guide to Learn R with AI in DQLab",
    issuer: "DQLab",
    date: "January 2025",
    credentialId: "#DQLABAI002CBIGBR",
    link: "https://academy.dqlab.id/Certificate_check/result/DQLABAI002CBIGBR#mycertificate",
    logo: DQLabLogo,
  },
  {
    id: "cert-08",
    title: "Introduction to Data Science with R",
    issuer: "DQLab",
    date: "January 2025",
    credentialId: "#DQLABBGINRPCPGTC", 
    link: "https://academy.dqlab.id/Certificate_check/result/DQLABBGINRPCPGTC#mycertificate",
    logo: DQLabLogo,
  },
  {
    id: "cert-07",
    title: "R Fundamental for Data Science",
    issuer: "DQLab",
    date: "January 2025",
    credentialId: "#DQLABINTR1LBAIKB", 
    link: "https://academy.dqlab.id/Certificate_check/result/DQLABINTR1LBAIKB#mycertificate",
    logo: DQLabLogo,
  },
  {
    id: "cert-06",
    title: "Cloud Essential Knowledge Badge Assessment",
    issuer: "Amazon Web Services (AWS)",
    date: "July 2024",
    credentialId: "-", 
    link: "https://skillbuilder.aws/learn/63URRERNTS/cloud-essentials-knowledge-badge-assessment/VYB4663QV9",
    logo: AWSLogo,
  },
  {
    id: "cert-05",
    title: "Belajar Dasar AI",
    issuer: "Dicoding Indonesia",
    date: "June 2024",
    credentialId: "QLZ976DJ7P5D",
    link: "https://www.dicoding.com/certificates/QLZ976DJ7P5D",
    logo: DicodingLogo,
  },
  {
    id: "cert-04",
    title: "Introduction to Java",
    issuer: "Sololearn",
    date: "June 2024",
    credentialId: "CC-EFOCFSYK",
    link: "https://www.sololearn.com/certificates/CC-EFOCFSYK",
    logo: SoloLearnLogo,
  },
  {
    id: "cert-03",
    title: "Belajar Pemrograman Prosedural dengan Python",
    issuer: "Dicoding Indonesia",
    date: "January 2024",
    credentialId: "81P2VEN0JPOY",
    link: "https://www.dicoding.com/certificates/81P2VEN0JPOY",
    logo: DicodingLogo,
  },
  {
    id: "cert-02",
    title: "Introduction to C++",
    issuer: "Sololearn",
    date: "January 2024",
    credentialId: "CC-MGG7AQ6B",
    link: "https://www.sololearn.com/certificates/CC-MGG7AQ6B",
    logo: SoloLearnLogo,
  },
  {
    id: "cert-01",
    title: "Belajar Dasar Pemrograman Web",
    issuer: "Dicoding Indonesia",
    date: "December 2023",
    credentialId: "KEXL80Y10ZG2",
    link: "https://www.dicoding.com/certificates/KEXL80Y10ZG2",
    logo: DicodingLogo,
  },
];